app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
    
login: 
    path: /login
    defaults: { _controller:AppBundle:Security:login }
    
login_check:
    path: /login_check
    
    
logout:
    path: /logout
