project_list:
    path: /list/{page}
    defaults: { _controller: AppBundle:Project:list, page:1 }
    requirements:
        page: \d+

project_myProjects:
    path: /MesProjets
    defaults: { _controller: AppBundle:Project:myProjects}

project_detail:
    path: /{id}
    defaults: { _controller: AppBundle:Project:detail, id: -1}
    requirements:
        id: \d+

project_add:
    path: /add
    defaults : { _controller: AppBundle:Project:add }
    
project_update:
    path: /update/{id}
    defaults : { _controller: AppBundle:Project:update, id: -1}
    
project_editSkill:
    path: /editSkill
    defaults : { _controller: AppBundle:Project:editProjectSkill}
    requirements:
        _method:  POST