user_list:
    path: /list/{page}
    defaults: { _controller: AppBundle:User:index, page: 1 }
    requirements:
        page: \d+
    
user_profile:
    path: /{id}
    defaults: { _controller: AppBundle:User:profile, id: -1 }
    requirements :
        id: \d+
        
user_update:
    path: /{id}/update
    defaults: { _controller: AppBundle:User:updateProfil, id: -1 }

user_updateskill:
    path: /{id}/updateSkill
    defaults: { _controller: AppBundle:User:updateSkillProfil, id: -1 }
    
user_addSkillUser:
    path: /editSkill
    defaults: { _controller: AppBundle:User:addSkillUser }
    
user_notif:
    path: /{id}/readNotif/{type}-{notifId}
    defaults: { _controller: AppBundle:User:notif }
    requirements:
        _method: POST