user_list:
    path: /list/{page}
    defaults: { _controller: AppBundle:User:index, page: 1 }
    requirements:
        page: \d+
    
user_profile:
    path: /{id}
    defaults: { _controller: AppBundle:User:profile, id: -1 }
    requirements :
        id: \d+
        
user_update:
    path: /update/{id}
    defaults: { _controller: AppBundle:User:update, id: -1 }