<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository {	
   public function findUserNotifications($id){
		$query = $this->createQueryBuilder('n')
				->where('n.user=:id')
                ->setParameter('id', $id);
		return $query->getQuery()->getResult();
	}
}
