<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function findProjectsEager(){
        $query = $this->createQueryBuilder('a')
                ->leftJoin('a.user', 'u')
                ->addSelect('u');
                
        return $query->getQuery()->getResult();
    }
	
	public function getProjectsStatusPositive(){
        $query = $this->createQueryBuilder('p')
                ->where('p.status >= 0')
				->orderBy('p.creationDate', 'DESC');
        return $query->getQuery()->getResult();
    } 
}