<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

	public function findUsersEager() {

		$query = $this->createQueryBuilder('u')
				->leftJoin('u.userSkills', 'us')
				->addSelect('us')
				->leftJoin('us.skill', 's')
				->addSelect('s');

		return $query->getQuery()->getResult();
	}

	public function findOneUserEager($id) {
		$query = $this->createQueryBuilder('u')
				->leftJoin('u.promo', 'p')
				->addSelect('p')
				->leftJoin('u.image', 'i')
				->addSelect('i')
				->leftJoin('u.userSkills', 'us')
				->addSelect('us')
				->leftJoin('us.skill', 's')
				->addSelect('s')
				->leftJoin('s.parent', 'pa')
				->addSelect('pa')
				->where('u.id=:id')
				->setParameter('id', $id);
		return $query->getQuery()->getOneOrNullResult();
	}

	public function getUsersWithProject() {
		$query = $this->createQueryBuilder('u')
				->leftjoin('u.userProjects', 'up')
				->addSelect('up')
				->leftjoin('up.project', 'p')
				->addSelect('p')
				->orderBy('u.lastname', 'DESC');
		return $query->getQuery()->getResult();
	}
}
