<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProjectRepository extends EntityRepository
{
	
    public function getUserProjectByProjectAndUser($projectId, $userId){
		$query = $this->createQueryBuilder('up')
				->andWhere('up.project=:projectId')
                ->setParameter('projectId', $projectId)
				->andWhere('up.user=:userId')
				->setParameter('userId', $userId);
		return $query->getQuery()->getOneOrNullResult();
	}
	
	public function getProjectInvitationModale($id){
		$query = $this->createQueryBuilder('up')
				->leftJoin('up.project', 'p')
				->addSelect('p')
				->andWhere('up.user=:userId')
				->setParameter('userId', $id)
				->andWhere('up.status = 4');
		
		return $query->getQuery()->getResult();
	}

}
